spring.application.name=auth
server.port=8081

# Base de datos independiente (SRS - RNF06)
spring.datasource.url=jdbc:mysql://localhost:3306/db_smartlogix_auth?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT — 2 horas de expiración (SRS - RNF02 y 6.2.6)
jwt.secret=X2@pQ!8zH#1kM$eY6%WnR3vG7*CdT4bU^aL0sJ9fB5h
jwt.expiration=7200000
jwt.prefix=Bearer
jwt.header=Authorization

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
