spring.application.name=bff
server.port=8084

# JWT (mismo secret que los microservicios)
jwt.secret=X2@pQ!8zH#1kM$eY6%WnR3vG7*CdT4bU^aL0sJ9fB5h
jwt.expiration=7200000
jwt.prefix=Bearer
jwt.header=Authorization

# URLs de los microservicios
services.auth.url=http://localhost:8081
services.inventario.url=http://localhost:8082
services.pedidos.url=http://localhost:8083
services.envios.url=http://localhost:8085

# Circuit Breaker — auth
resilience4j.circuitbreaker.instances.auth.slidingWindowSize=5
resilience4j.circuitbreaker.instances.auth.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.auth.failureRateThreshold=50
resilience4j.circuitbreaker.instances.auth.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.auth.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.auth.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker — inventario
resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventario.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventario.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.inventario.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker — pedidos
resilience4j.circuitbreaker.instances.pedidos.slidingWindowSize=5
resilience4j.circuitbreaker.instances.pedidos.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.pedidos.failureRateThreshold=50
resilience4j.circuitbreaker.instances.pedidos.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.pedidos.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.pedidos.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker — envios
resilience4j.circuitbreaker.instances.envios.slidingWindowSize=5
resilience4j.circuitbreaker.instances.envios.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.envios.failureRateThreshold=50
resilience4j.circuitbreaker.instances.envios.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.envios.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.envios.automaticTransitionFromOpenToHalfOpenEnabled=true

# Fechas como ISO string
spring.jackson.serialization.write-dates-as-timestamps=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
