spring.application.name=${artifactId}
server.port=${serverPort}

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/smartlogix_${artifactId}?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=smartlogix-secret-key
jwt.expiration=86400000
